services:
  db:
    image: postgres
    volumes:
      - ./qulture-challenge-api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  api:
    build:
      context: ./qulture-challenge-api
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./qulture-challenge-api:/qulture-challenge-api
    ports:
      - "3001:3000"
    depends_on:
      - db

  nextjs:
    build:
      context: ./qulture-challenge-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./qulture-challenge-client:/qulture-challenge-client
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    depends_on:
      - api
